In [1]:
import numpy as np


In [2]:
np.random.random()

0.30514832832554084

In [3]:
np.random.random()

0.2751587824544932

In [4]:
np.random.random()

0.7154634343584828

In [8]:
np.random.seed(100)
.random.random()
np.random.random()
np.random.random()
np.random.random()

0.8447761323199037

In [11]:
np.random.seed(100)
print(np.random.randint(12))
print(np.random.randint(13))
print(np.random.randint(14))
print(np.random.randint(15))

8
8
3
7


In [12]:
np.random.random([3,3])

array([[0.42451759, 0.84477613, 0.00471886],
       [0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195]])

In [19]:
np.random.randint(low=20,high=30,size=[4,5])

array([[23, 25, 20, 29, 23],
       [26, 23, 24, 27, 26],
       [23, 29, 20, 24, 24],
       [25, 27, 26, 26, 22]])

In [20]:
a=[12,34,56,78,90,32]

In [22]:
np.random.choice(a,size=[4,5])

array([[90, 56, 32, 90, 34],
       [56, 56, 12, 56, 56],
       [78, 32, 90, 56, 90],
       [78, 32, 34, 12, 12]])

In [24]:
a=np.random.random([5,6])

In [25]:
a

array([[0.69773491, 0.8596183 , 0.62532376, 0.98240783, 0.97650013,
        0.16669413],
       [0.02317814, 0.16074455, 0.92349683, 0.95354985, 0.21097842,
        0.36052525],
       [0.54937526, 0.27183085, 0.46060162, 0.69616156, 0.5003559 ,
        0.71607099],
       [0.52595594, 0.00139902, 0.39470029, 0.49216697, 0.40288033,
        0.3542983 ],
       [0.50061432, 0.44517663, 0.09043279, 0.27356292, 0.9434771 ,
        0.02654464]])

In [26]:
b=np.round(a,2)

In [27]:
b

array([[0.7 , 0.86, 0.63, 0.98, 0.98, 0.17],
       [0.02, 0.16, 0.92, 0.95, 0.21, 0.36],
       [0.55, 0.27, 0.46, 0.7 , 0.5 , 0.72],
       [0.53, 0.  , 0.39, 0.49, 0.4 , 0.35],
       [0.5 , 0.45, 0.09, 0.27, 0.94, 0.03]])

In [28]:
c=b.astype(int)

In [29]:
c

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
x=np.arange(12)

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
x.shape

(12,)

In [33]:
x.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
x.reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [51]:
y=np.random.random([4,5,6])

In [52]:
y

array([[[5.54476808e-01, 6.47167332e-01, 1.85474159e-01, 2.71978204e-01,
         1.48438658e-01, 3.03041706e-02],
        [9.39255584e-01, 3.46754130e-01, 1.09564604e-01, 3.78326996e-01,
         3.84079459e-01, 6.65423688e-01],
        [2.44490929e-01, 6.61480974e-01, 9.84928838e-02, 5.80862748e-01,
         1.06865505e-01, 5.48254507e-01],
        [5.19751708e-01, 2.96234118e-01, 4.55729051e-01, 3.86665201e-02,
         5.99003025e-01, 4.86759475e-04],
        [5.01813594e-01, 5.01726122e-01, 6.06696959e-02, 9.49836939e-01,
         6.08659045e-01, 6.72002684e-01]],

       [[4.62773524e-01, 7.04273095e-01, 1.81067141e-01, 6.47582177e-01,
         5.68108735e-01, 9.54138315e-01],
        [7.96690239e-01, 5.85310393e-01, 4.55354967e-01, 7.38451531e-01,
         8.12236278e-01, 9.27291174e-01],
        [8.26375607e-01, 2.99565977e-02, 7.72802822e-01, 5.21777394e-01,
         8.85387332e-01, 4.58561667e-01],
        [5.40722576e-01, 9.07764998e-01, 5.56310040e-01, 1.87114722e-01,
     

In [39]:
z=y.reshape(-1)

In [40]:
z

array([0.84960733, 0.25446654, 0.87755554, 0.43513019, 0.72949434,
       0.41264077, 0.19083605, 0.70601952, 0.24063282, 0.85132443,
       0.82410229, 0.52521179, 0.38634079, 0.59088079, 0.13752361,
       0.80827041, 0.96582582, 0.7797958 , 0.23933508, 0.86726041,
       0.80811501, 0.06368112, 0.2312283 , 0.58968545, 0.13748695,
       0.6784407 , 0.99219069, 0.28575198, 0.76091276, 0.04652717,
       0.33253591, 0.94455279, 0.63651704, 0.60184861, 0.92818468,
       0.18167941, 0.01782318, 0.19007218, 0.5218718 , 0.49582199,
       0.80049121, 0.85943631, 0.21295603, 0.43726884, 0.42161751,
       0.05471738, 0.00993369, 0.78976568, 0.27531322, 0.71774   ,
       0.42135592, 0.14333587, 0.19252168, 0.31381523, 0.80517017,
       0.01262583, 0.04910597, 0.56600038, 0.6868107 , 0.72681091,
       0.47969376, 0.36765672, 0.8399701 , 0.45416355, 0.32136584,
       0.09271987, 0.06043793, 0.09095117, 0.68270646, 0.68073577,
       0.24317417, 0.64046144, 0.06913918, 0.87291996, 0.10960

In [41]:
z.shape

(120,)

In [42]:
a=np.arange(5)

In [43]:
a

array([0, 1, 2, 3, 4])

In [44]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [46]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [47]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [48]:
a.sum()

10

In [50]:
np.sum(a)

10

In [53]:
y

array([[[5.54476808e-01, 6.47167332e-01, 1.85474159e-01, 2.71978204e-01,
         1.48438658e-01, 3.03041706e-02],
        [9.39255584e-01, 3.46754130e-01, 1.09564604e-01, 3.78326996e-01,
         3.84079459e-01, 6.65423688e-01],
        [2.44490929e-01, 6.61480974e-01, 9.84928838e-02, 5.80862748e-01,
         1.06865505e-01, 5.48254507e-01],
        [5.19751708e-01, 2.96234118e-01, 4.55729051e-01, 3.86665201e-02,
         5.99003025e-01, 4.86759475e-04],
        [5.01813594e-01, 5.01726122e-01, 6.06696959e-02, 9.49836939e-01,
         6.08659045e-01, 6.72002684e-01]],

       [[4.62773524e-01, 7.04273095e-01, 1.81067141e-01, 6.47582177e-01,
         5.68108735e-01, 9.54138315e-01],
        [7.96690239e-01, 5.85310393e-01, 4.55354967e-01, 7.38451531e-01,
         8.12236278e-01, 9.27291174e-01],
        [8.26375607e-01, 2.99565977e-02, 7.72802822e-01, 5.21777394e-01,
         8.85387332e-01, 4.58561667e-01],
        [5.40722576e-01, 9.07764998e-01, 5.56310040e-01, 1.87114722e-01,
     

In [54]:
q=y.T

In [55]:
q

array([[[5.54476808e-01, 4.62773524e-01, 3.03847230e-02, 4.50877476e-01],
        [9.39255584e-01, 7.96690239e-01, 3.81007271e-01, 2.11281884e-01],
        [2.44490929e-01, 8.26375607e-01, 8.06285873e-01, 9.95265402e-01],
        [5.19751708e-01, 5.40722576e-01, 1.23449693e-01, 7.02679904e-02],
        [5.01813594e-01, 3.80091658e-01, 1.33674962e-01, 1.35636138e-01]],

       [[6.47167332e-01, 7.04273095e-01, 7.78173527e-01, 3.29700978e-01],
        [3.46754130e-01, 5.85310393e-01, 4.05734533e-01, 8.65423224e-02],
        [6.61480974e-01, 2.99565977e-02, 8.04391081e-01, 2.00628509e-02],
        [2.96234118e-01, 9.07764998e-01, 6.19291979e-02, 8.84373643e-02],
        [5.01726122e-01, 8.08684490e-01, 1.80345169e-01, 8.58726973e-01]],

       [[1.85474159e-01, 1.81067141e-01, 1.81383860e-01, 4.93512042e-01],
        [1.09564604e-01, 4.55354967e-01, 6.58965435e-01, 3.87257418e-01],
        [9.84928838e-02, 7.72802822e-01, 1.47700436e-01, 1.08198229e-01],
        [4.55729051e-01, 5.5631004

In [59]:
z=np.arange(6)

In [70]:
z.argmax()

5

In [62]:
o=z.reshape(3,2)

In [63]:
o

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
m=np.random.random([2,3])

In [65]:
m

array([[0.51933798, 0.34333345, 0.65877293],
       [0.28279025, 0.50246643, 0.30327752]])

In [66]:
np.dot(o,m)

array([[0.28279025, 0.50246643, 0.30327752],
       [1.88704672, 2.19406619, 2.22737842],
       [3.49130319, 3.88566595, 4.15147932]])